const SELECT_PIZZERIA = "SELECT_PIZZERIA";
const TOGGLE_PIZZERIA = "TOGGLE_PIZZERIA";
const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
const DELETE_ORDER_ITEM = "DELETE_ORDER_ITEM";

module.exports = {
  SELECT_PIZZERIA,
  TOGGLE_PIZZERIA,
  ADD_ORDER_ITEM,
  DELETE_ORDER_ITEM
};
